.catalog:
  name: deliflow-ui-and-services
  version: 1.0.0-rancher2
  description: |
    Deliflow UI(Web) And Services
  uuid: deliflow-ui-and-services-0
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "app_service_home"
      description: |
        The Web app's root url example: https://www.exmaple.org/
      label: Web App Home url
      default: "https://ui.dev.twleansw.com"
      required: true
      type: "string"
    - variable: "gocdserver_ip"
      description: |
        Choose the gocd service to connect.
      label: "Gocd server stack/service"
      default: "deliflow-external-services/deliflow-gocd-server"
      required: true
      type: "service"
    - variable: "rancherserver_ip"
      description: |
        Choose the Rancher service to connect.
      label: "Rancher server stack/service"
      default: "deliflow-external-services/deliflow-rancher-server"
      required: true
      type: "service"
    - variable: "sonarserver_ip"
      description: |
        Choose the SonarQube server to connect.
      label: "SonarQube server stack/service"
      default: "deliflow-external-services/deliflow-sonar-server"
      required: true
      type: "service"
    - variable: "artifactoryserver_ip"
      description: |
        Choose the artifactory service to connect.
      label: "Artifactory server stack/service"
      default: "deliflow-external-services/deliflow-artifactory-server"
      required: true
      type: "service"
    - variable: "mongoserver_ip"
      description: |
        Choose the mongodb to connect.
      label: "MongoDB service stack/service"
      default: "deliflow-external-services/deliflow-mongo-server"
      required: true
      type: "service"
    - variable: "rabbitmqserver_ip"
      description: |
        Choose the rabbitmq to connect.
      label: "Rabbitmq server stack/service"
      default: "deliflow-external-services/deliflow-rabbitmq-server"
      required: true
      type: "service"
    - variable: "ldapserver_ip"
      description: |
        Choose the LDAP to connect.
      label: "LDAP server stack/service"
      default: "deliflow-external-services/deliflow-openldap-server"
      required: true
      type: "service"
    - variable: "docker_image_tag"
      description: |
        Docker Image Tag : dev/rc/release.
      label: Docker Image Tag
      default: "dev"
      required: true
      type: "string"
    - variable: "host_env_label"
      description: |
        Host Env Label(soft)
      label: "Host Env Label"
      default: "dev"
      required: true
      type: "string"
deliflow-code-metrics-service:
  scale: 1
deliflow-identity-service:
  scale: 1
deliflow-discovery-service:
  scale: 1
deliflow-cd-metrics-service:
  scale: 1
deliflow-quartz-service:
  scale: 1 
deliflow-graph-service:
  scale: 1
deliflow-cas-service:
  scale: 1
deliflow-webapp:
  scale: 1