.catalog:
  name: deliflow-ui-and-services
  version: 1.0.0-rancher2
  description: |
    Deliflow UI(Web) And Services
  uuid: deliflow-ui-and-services-0
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "app_service_home"
      description: |
        The Web app's root url example: https://www.exmaple.org/
      label: Web App Home url
      default: "https://dev.ui.twleansw.com"
      required: true
      type: "string"
    - variable: "gocdserver_ip"
      description: |
        Choose the gocd service to connect.
      label: "Gocd server stack/service"
      default: "gocd-sever/gocd-server"
      required: true
      type: "service"
    - variable: "rancherserver_ip"
      description: |
        Choose the Rancher service to connect.
      label: "Rancher server stack/service"
      default: "rancher-sever/rancher-server"
      required: true
      type: "service"
    - variable: "sonarserver_ip"
      description: |
        Choose the SonarQube server to connect.
      label: "SonarQube server stack/service"
      default: "sonar-sever/sonar-server"
      required: true
      type: "service"
    - variable: "artifactoryserver_ip"
      description: |
        Choose the artifactory service to connect.
      label: "Artifactory server stack/service"
      default: "artifactory-sever/artifactory-server"
      required: true
      type: "service"
    - variable: "mongoserver_ip"
      description: |
        Choose the mongodb to connect.
      label: "MongoDB service stack/service"
      default: "mongo-sever/mongo-server"
      required: true
      type: "service"
    - variable: "rabbitmqserver_ip"
      description: |
        Choose the rabbitmq to connect.
      label: "Rabbitmq server stack/service"
      default: "rabibitmq-sever/rabbitmq-server"
      required: true
      type: "service"
    - variable: "docker_image_tag"
      description: |
        Docker Image Tag : latest/release etc.
      label: Docker Image Tag
      default: "latest"
      required: true
      type: "string"
    - variable: "host_env_label"
      description: |
        Host Env Label(soft)
      label: "Host Env Label"
      default: "dev"
      required: true
      type: "string"
deliflow-code-metrics-service:
  scale: 1
deliflow-identity-service:
  scale: 1
deliflow-discovery-service:
  scale: 1
deliflow-cd-metrics-service:
  scale: 1
deliflow-quartz-service:
  scale: 1 
deliflow-graph-service:
  scale: 1
deliflow-webapp:
  scale: 1