version: '2'
services:
  deliflow-mongo-server:
    image: mongo:3.3.15
    stdin_open: true
    tty: true
    ports:
    - 27017:27017/tcp
    command:
    - --auth
    labels:
      io.ranhcer.container.hostname_override: container_name
  deliflow-gocd-server:
    image: gocd/gocd-server:17.1.0
    network_mode: bridge
    tty: true
    volumes_from:
    - gocd-volumes
    ports:
    - 8153:8153/tcp
    - 8154:8154/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: gocd-volumes
  deliflow-artifactory-server:
    image: reg.dev.twleansw.com/leansw/artifactory-oss:4.13.0
    stdin_open: true
    network_mode: bridge
    tty: true
    volumes_from:
    - artifactory-data
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.sidekicks: artifactory-data
      io.ranhcer.container.hostname_override: container_name
  deliflow-phpldapadmin-server:
    image: reg.dev.twleansw.com/leansw/phpldapadmin:0.6.11-xfs
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
    tty: true
    links:
    - deliflow-openldap-server:ldap-host
    ports:
    - 6443:443/tcp
    - 6080:80/tcp
    labels:
      io.rancher.container.hostname_override: container_name
  deliflow-openldap-server:
    image: reg.dev.twleansw.com/leansw/openldap:1.1.6-xfs
    environment:
      LDAP_ADMIN_PASSWORD: Leanswdev1
      LDAP_DOMAIN: deliflow.com
      LDAP_ORGANISATION: Deliflow
    stdin_open: true
    tty: true
    ports:
    - 389:389/tcp
    - 636:636/tcp
    labels:
      io.ranhcer.container.hostname_override: container_name
  sonar-volume:
    image: sonarqube:5.6.5
    volumes:
    - /opt/sonarqube
    tty: true
    command:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  gocd-volumes:
    image: gocd/gocd-server:17.1.0
    volumes:
    - /plugins
    - /var/lib/go-server
    - /var/log/go-server
    - /etc/go
    tty: true
    command:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  rancher-server:
    image: rancher/external-service
  deliflow-mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sonarqube
      MYSQL_PASSWORD: sonar
      MYSQL_ROOT_PASSWORD: Leanswdev1
      MYSQL_USER: sonar
    stdin_open: true
    tty: true
    network_mode: host
    ports:
    - 3306:3306/tcp
    labels:
      io.ranhcer.container.hostname_override: container_name
  deliflow-rabbitmq-server:
    image: rabbitmq:3.6.5
    stdin_open: true
    tty: true
    ports:
    - 5672:5672/tcp
    labels:
      io.ranhcer.container.hostname_override: container_name
  deliflow-sonar-server:
    image: sonarqube:5.6.5
    environment:
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:mysql://mysql.demo.twleansw.com/sonarqube?useUnicode=true&characterEncoding=utf8
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_LOG_LEVEL: DEBUG
    stdin_open: true
    tty: true
    volumes_from:
    - sonar-volume
    ports:
    - 9000:9000/tcp
    - 9092:9092/tcp
    labels:
      io.rancher.sidekicks: sonar-volume
      io.ranhcer.container.hostname_override: container_name
  artifactory-data:
    image: reg.dev.twleansw.com/leansw/artifactory-oss:4.13.0
    volumes:
    - /var/opt/jfrog/artifactory
    tty: true
    command:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
