name: deliflow-external-services
description: Deliflow External Services
version: 1.0.0-rancher1
category: Continuous Integration
maintainer: "ylli@thoughtworks.com"
license:
projectURL: "www.thoughtworks.com"
minimum_rancher_version: v1.0.0
