name: deliflow-external-services
description: Deliflow External Services
version: 1.0.2-rancher2-noldap
category: Continuous Integration
maintainer: "ylli@thoughtworks.com"
license:
projectURL: "www.thoughtworks.com"
minimum_rancher_version: v1.0.0
