deliflow-code-metrics-service:
  ports:
  - 9003:9003/tcp
  external_links:
  - ${sonarserver_ip}:sonar-server
  - ${mongoserver_ip}:mongo-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=${host_env_label}
  tty: true
  entrypoint:
  - bash
  - -c
  - >
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata/latest/self/container/primary_ip) && 
    echo $$EUREKA_INSTANCE_HOSTNAME && 
    PROFILE=$${ACTIVE_PROFILE:=docker} && 
    java -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /code-metrics.jar 
    --logging.level.sun.net.www.http=DEBUG 
    --quartz.enabled=${code_metrics_quartz_enable} 
    --eureka.instance.preferIpAddress=false 
    --spring.profiles.active=$$PROFILE  
    --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: registry.aliyuncs.com/leansw/code-metrics
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-identity-service:
  ports:
  - 2400:2400/tcp
  external_links:
  - ${mysqlserver_ip}:mysql-server
  - ${goserver_id}:gocd-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=${host_env_label}
  tty: true
  entrypoint:
  - bash
  - -c
  - >
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata/latest/self/container/primary_ip)&& 
    echo $$EUREKA_INSTANCE_HOSTNAME  && 
    PROFILE=$${ACTIVE_PROFILE:=docker} && 
    HOST=$${GOCD_SERVER_HOST:=gocd-server} && 
    PORT=$${GOCD_SERVER_PORT:=8153} && 
    ROOT_PATH=$${GOCD_SERVER_ROOT:=/go} && 
    USERNAME=$${GOCD_USERNAME:=admin} && 
    PASSWORD=$${GOCD_PASSWORD:=badger} && 
    java -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /identity-services.jar 
    --spring.profiles.active=$$PROFILE 
    --gocd.server.host=http://$$HOST:$$PORT$$ROOT_PATH 
    --gocd.server.username=$$USERNAME 
    --gocd.server.password=$$PASSWORD  
    --eureka.instance.preferIpAddress=false 
    --quartz.enabled=${identity_quartz_enable} 
    --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: registry.aliyuncs.com/leansw/identity-services
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-discovery-service:
  ports:
  - 8761:8761/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=${host_env_label}
  tty: true
  image: registry.aliyuncs.com/leansw/discovery-service
  stdin_open: true
deliflow-cd-metrics-service:
  ports:
  - 9001:9001/tcp
  environment:
    RANCHER_URI: http://rancher-server:8080
    RANCHER_ACCESS_SECRET: 14E81ABF45359F074521
    RANCHER_SECRET_KEY: E7xmHz2h22iJWUpf1atDEnqsd2zzv9udHdsQkjjy
  external_links:
  - ${goserver_ip}:gocd-server
  - ${rancherserver_ip}:rancher-server
  - ${sonarserver_ip}:sonar-server
  - ${artifactoryserver_ip}:artifactory-server
  - ${mysqlserver_ip}:mysql-server
  - ${mongoserver_ip}:mongo-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=${host_env_label}
  tty: true
  entrypoint:
  - bash
  - -c
  - > 
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata/latest/self/container/primary_ip) &&
    echo $$EUREKA_INSTANCE_HOSTNAME && 
    PROFILE=$${ACTIVE_PROFILE:=docker} && 
    HOST=$${GOCD_SERVER_HOST:=gocd-server} && 
    PORT=$${GOCD_SERVER_PORT:=8153} && 
    ROOT_PATH=$${GOCD_SERVER_ROOT:=/go} && 
    USERNAME=$${GOCD_USERNAME:=admin} && 
    PASSWORD=$${GOCD_PASSWORD:=badger} && 
    java -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar cd-metrics.jar  
    --rancher.uri=$$RANCHER_URI  
    --rancher.secretKey=$$RANCHER_SECRET_KEY  
    --rancher.accessSecret=$$RANCHER_ACCESS_SECRET  
    --spring.profiles.active=$$PROFILE  
    --gocd.server.host=http://$$HOST:$$PORT$$ROOT_PATH  
    --gocd.server.username=$$USERNAME  
    --gocd.server.password=$$PASSWORD  
    --eureka.instance.preferIpAddress=false 
    --quartz.enabled=${code_metrics_quartz_enable}  
    --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: registry.aliyuncs.com/leansw/cd-metrics
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-webapp:
  ports:
  - 9900:9900/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=${host_env_label}
  tty: true
  entrypoint:
  - bash
  - -c
  - >
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata/latest/self/container/primary_ip) && 
    echo $$EUREKA_INSTANCE_HOSTNAME && 
    PROFILE=$${ACTIVE_PROFILE:=docker} && 
    java -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /deliflow-webapp.jar  
    --eureka.instance.preferIpAddress=false 
    --spring.profiles.active=$$PROFILE  
    --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: registry.aliyuncs.com/leansw/deliflow-webapp
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
