.catalog:
  name: deliflow-ui-and-services
  version: 1.0.0-rancher1
  description: |
    Deliflow UI(Web) And Services
  uuid: deliflow-ui-and-services-0 
  minimum_rancher_version: v0.59.0
deliflow-code-metrics-service:
  scale: 1
deliflow-identity-service:
  scale: 1
deliflow-discovery-service:
  scale: 1
deliflow-cd-metrics-service:
  scale: 1
deliflow-webapp:
  scale: 1
