deliflow-gocd-server:
  ports:
  - 8153:8153/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
     gocd/gocd-server:16.10.0
  stdin_open: true
deliflow-mongo-server:
  ports:
  - 27017:27017/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    mongo:3.3.15
  stdin_open: true
deliflow-mysql-server:
  ports:
  - 3306:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: Leanswdev1
    MYSQL_DATABASE: sonar
    MYSQL_USER: sonar
    MYSQL_PASSWORD: sonar
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    mysql:5.7.15
  stdin_open: true
deliflow-sonar-server:
  ports:
  - 9000:9000/tcp
  links:
  - deliflow-mysql-server:mysql
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: sonar
    SONARQUBE_JDBC_URL: jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    sonarqube:6.1-alpine
  stdin_open: true
deliflow-artifactory-server:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    mattgruter/artifactory:3.9.2
  stdin_open: true
deliflow-rabbitmq-server:
  ports:
  - 5672:5672/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    rabbitmq:3.6.5
  stdin_open: true
deliflow-elasticsearch-server:
  ports:
  - 9200:9200/tcp
  - 9300:9300/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    elasticsearch:2.4.1
  stdin_open: true
deliflow-kibana-server:
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
  - deliflow-elasticsearch-server:elasticsearch
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: kibana:4.6.1
