.catalog:
  name: deliflow-external-services
  version: 1.0.0-rancher1
  description: |
    Deliflow infrastructure services
  uuid: deliflow-external-services-v1
  minimum_rancher_version: v1.0.0

deliflow-gocd-server:
  scale: 1
deliflow-mongo-server:
  scale: 1
deliflow-mysql-server:
  scale: 1
deliflow-sonar-server:
  scale: 1
deliflow-artifactory-server:
  scale: 1
deliflow-rabbitmq-server:
  scale: 1
deliflow-rabbitmq-server:
  scale: 1
deliflow-kibana-server:
  scale: 1
