go-agent16-11-0-remote-docker:
  environment:
    GO_SERVER: gocd-server
    GOCD_SERVER: gocd-server
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: host_agent=true
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=go-agent16-11-0-remote-docker
    io.rancher.scheduler.affinity:host_label_ne: host_role=services
  tty: true
  image: reg.dev.twleansw.com/leansw/go_agent_docker:16.11.0-20
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /run/go-agent/pipelines:/run/go-agent/pipelines
  - /root:/root
  privileged: true
  net: host
