name: leansw-go-agents
description: |
  Go Agents for go leanSW
version: 1.0.3-rancher
category: Continuous Integration
maintainer: "ylli@thoughtworks.com"
license:
projectURL: "www.thoughtworks.com"
minimum_rancher_version: v0.59.0
