name: leansw-go-agents
description: "Go Agents for go leanSW"
version: 16.2.1-rancher-1
category: LeanSW
maintainer: "ylli@thoughtworks.com"
license: 
projectURL: "www.thoughtworks.com"
minimum_rancher_version: v1.0.2