deliflow-gocd-server:
  ports:
  - 8153:8153/tcp
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
     gocd/gocd-server:17.1.0
  stdin_open: true
deliflow-mongo-server:
  ports:
  - 27017:27017/tcp
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    mongo:3.3.15
  stdin_open: true
deliflow-mysql-server:
  ports:
  - 3306:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: Leanswdev1
    MYSQL_DATABASE: sonar
    MYSQL_USER: sonar
    MYSQL_PASSWORD: sonar
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    mysql:5.7.15
  stdin_open: true
deliflow-sonar-server:
  ports:
  - 9000:9000/tcp
  links:
  - deliflow-mysql-server:mysql
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: sonar
    SONARQUBE_JDBC_URL: jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    sonarqube:5.6.3
  stdin_open: true
deliflow-artifactory-server:
  ports:
  - 8081:8081/tcp
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image: reg.dev.twleansw.com/leansw/artifactory-oss:4.13.0
  stdin_open: true
deliflow-rabbitmq-server:
  ports:
  - 5672:5672/tcp
  labels:
    io.ranhcer.container.hostname_override: container_name
  tty: true
  image:
    rabbitmq:3.6.5
  stdin_open: true
