name: deliflow-quick-start
description: |
    Deliflow Quick Start
    All Deliflow Services + UI
    SonarQube  Artifactory  GoCD-server GoCD-agent MongoDB MySQL rabbitmq
version: 1.0.0-rancher1
category: Continuous Integration
maintainer: "ylli@thoughtworks.com"
license: 
projectURL: "www.thoughtworks.com"
minimum_rancher_version: v0.59.0