.catalog:
  name: deliflow-ui-and-services
  version: 1.0.3-rancher
  description: |
    Deliflow UI(Web) And Services
  uuid: deliflow-ui-and-services-1
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "gocdserver_ip"
      description: |
        Choose the gocd service to connect.
      label: "Gocd server stack/service"
      default: "deliflow-external-services/deliflow-gocd-server"
      required: true
      type: "service"
    - variable: "rancherserver_ip"
      description: |
        Choose the Rancher service to connect.
      label: "Rancher server stack/service"
      default: "deliflow-external-services/deliflow-rancher-server"
      required: true
      type: "service"
    - variable: "sonarserver_ip"
      description: |
        Choose the SonarQube server to connect.
      label: "SonarQube server stack/service"
      default: "deliflow-external-services/deliflow-sonar-server"
      required: true
      type: "service"
    - variable: "zipkinserver_ip"
      description: |
        Choose the Zipkin server to connect.
      label: "Zipkin server stack/service"
      default: "deliflow-zipkin-server/zipkin"
      required: true
      type: "service"
    - variable: "artifactoryserver_ip"
      description: |
        Choose the artifactory service to connect.
      label: "Artifactory server stack/service"
      default: "deliflow-external-services/deliflow-artifactory-server"
      required: true
      type: "service"
    - variable: "mongoserver_ip"
      description: |
        Choose the mongodb to connect.
      label: "MongoDB service stack/service"
      default: "deliflow-external-services/deliflow-mongo-server"
      required: true
      type: "service"
    - variable: "rabbitmqserver_ip"
      description: |
        Choose the rabbitmq to connect.
      label: "Rabbitmq server stack/service"
      default: "deliflow-external-services/deliflow-rabbitmq-server"
      required: true
      type: "service"
    - variable: "ldapserver_ip"
      description: |
        Choose the LDAP to connect.
      label: "LDAP server stack/service"
      default: "deliflow-external-services/deliflow-openldap-server"
      required: true
      type: "service"
    - variable: "docker_image_tag"
      description: |
        Docker Image Tag : dev/rc/release.
      label: Docker Image Tag
      default: "dev"
      required: true
      type: "string"
    - variable: "cas_domain_name"
      description: |
        cas service domain name;
      label: cas domain name
      default: "cas.demo.twleansw.com"
      required: true
      type: "string"
    - variable: "ui_domain_name"
      description: |
        deliflow ui domain name;
      label: ui domain name
      default: "ui.demo.twleansw.com"
      required: true
      type: "string"
version: '2'
services:
  deliflow-cas-service:
    scale: 1
    start_on_create: true
  gocd-server:
    start_on_create: true
  deliflow-identity-service:
    scale: 1
    start_on_create: true
  deliflow-quartz-service:
    scale: 1
    start_on_create: true
  deliflow-code-metrics-service:
    scale: 1
    start_on_create: true
  deliflow-discovery-service:
    scale: 1
    start_on_create: true
  rabbitmq-server:
    start_on_create: true
  eureka-server:
    start_on_create: true
  deliflow-cd-metrics-service:
    scale: 1
    start_on_create: true
  artifactory-server:
    start_on_create: true
  sonar-server:
    start_on_create: true
  rancher-server:
    start_on_create: true
  zipkin-server:
    start_on_create: true
  deliflow-webapp:
    scale: 1
    start_on_create: true
  mongo-server:
    start_on_create: true
