go-agent16-9-0-dind:
  environment:
    GO_SERVER: gocd-server
  external_links:
  - ${goserver_ip}:gocd-server
  - ${goserver_ip}:go-server
  - ${rancherserver_ip}:rancher-server
  - ${artifactory_server_ip}:artifactory.server
  labels:
    io.rancher.sidekicks: go-agent16-9-0-dind-data
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: registry.cn-hangzhou.aliyuncs.com/leansw/go_agent_dind:16.9.0
  volumes_from:
  - go-agent16-9-0-dind-data
  stdin_open: true
  privileged: true
go-agent16-9-0-dind-data:
  labels:
    io.rancher.container.start_once: 'true'
  command:
  - cat
  tty: true
  image: registry.aliyuncs.com/leansw/go_agent_m2_data
  volumes:
  - /root/.m2
  - /run/go-agent/pipelines
  stdin_open: true
