go-agent16-9-0-dind:
  external_links:
  - ${goserver_ip}:gocd-server
  - ${goserver_ip}:go-server
  - ${rancherserver_ip}:rancher-server
  - ${artifactory_server_ip}:artifactory.server
  log_driver: ''
  environment:
  - AGENT_MEM=${mem_initial}m
  - AGENT_MAX_MEM=${mem_max}m
  labels:
    io.rancher.sidekicks: go-agent16-9-0-dind-data
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 223.5.5.5
  - 223.6.6.6
  log_opt: {}
  image: registry.cn-hangzhou.aliyuncs.com/leansw/go_agent_dind:16.9.0
  volumes_from:
  - go-agent16-2-1-java8-data
  stdin_open: true
go-agent16-9-0-dind-data:
  labels:
    io.rancher.container.start_once: 'true'
  command:
  - cat
  tty: true
  image: registry.aliyuncs.com/leansw/go_agent_m2_data
  volumes:
  - /var/go/.m2
  - /var/lib/go-agent/pipelines
  stdin_open: true
